apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hellosvc
  namespace: knative-demo
spec:
  template:
    metadata:
      name: hellosvc-rev2
    spec:
      containers:
        - image: 443247825008.dkr.ecr.us-east-1.amazonaws.com/gitops-argocd:d42074ada2926894520b6380ab1c92b433d6ae82
          ports:
            - containerPort: 80
