apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hellosvc
  namespace: knative-demo
spec:
  template:
    metadata:
      name: hellosvc--main-839572c-rev3
    spec:
      containers:
        - image: 443247825008.dkr.ecr.us-east-1.amazonaws.com/gitops-argocd:main-839572c
          ports:
            - containerPort: 80
