apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hellosvc
  namespace: knative-demo
  lables: 
     app: hellosvc 
spec:
  template:
    metadata:
      name: hellosvc-main-839572c-rev8
    spec:
      selector:
         app: hellosvc
      containers:
        - image: 443247825008.dkr.ecr.us-east-1.amazonaws.com/gitops-argocd:main-839572
          ports:
            - containerPort: 80
