apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hellosvc
  namespace: knative-demo
  labels: 
    app: hellosvc 
spec:
  template :
    metadata:
      name: hellosvc-main-839572c-rev8
    spec: 
      containers:
        - image: 443247825008.dkr.ecr.us-east-1.amazonaws.com/gitops-argocd:main-839572
          ports:
            - containerPort: 80
            
  traffic:
  - tag: current
    revisionName: hellosvc-main-bc92df0-rev2
    percent: 100
  - tag: latest
    latestRevision: true
    percent: 0
