apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hellosvc
  namespace: knative-demo
spec:
  template:
    metadata:
      name: hellosvc-rev1
    spec:
      containers:
        - image: 443247825008.dkr.ecr.us-east-1.amazonaws.com/gitops-argocd:main-839572c
          ports:
            - containerPort: 80
  traffic:
  - tag: current
    revisionName: hellosvc-main-bc92df0-rev2 
    percent: 100
  - tag: latest
    latestRevision: true
    percent: 0 
